# Generated by Django 2.0.1 on 2018-03-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_auto_20180322_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.DeleteModel(
            name='todo',
        ),
        migrations.AddField(
            model_name='tododetails',
            name='todotitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.TodoTitle'),
        ),
    ]
