# Generated by Django 2.0.1 on 2018-03-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20180326_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoDetails',
            new_name='TodoDetail',
        ),
    ]
