# Generated by Django 2.0.1 on 2018-03-29 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 7, 12, 8, 76126, tzinfo=utc)),
        ),
    ]
