# Generated by Django 2.0.1 on 2018-04-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_book_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
